### ISSUE TITLE
Should we use --save or --save-dev

### ISSUE THREAD

**Issue by chmac** [Xabadu/react-native-jest-mocks#10]
I noticed that `jest` and it's associated packages are in my `devDependencies` section rather than `dependencies`. Should this package also be in `devDependencies`?

If so, suggest a small tweak to the README to `npm --save-dev` or `yarn add --dev`.

Thanks for this package, super helpful to test react-native apps with jest. 👍

**Comment by Xabadu** [comment]
Hey, thanks for opening this issue and using this package. You're absolutely right. I've updated the README with the new installation instructions.
