### ISSUE TITLE
Adding `react-native-localize`

### ISSUE THREAD

**Issue by keyserfaty** [Xabadu/react-native-jest-mocks#16]
Hi! Thanks for the library, been wanting something like this for a while.
I recently had to configure `react-native-localize` and notice that they have a suggested mock in their docs. Would you be open to adding it to the library? I can open a PR.

**Comment by Xabadu** [comment]
Hi, @keyserfaty. Thanks for reaching out!

Absolutely! More than happy to review your PR and include it.

**Comment by Xabadu** [comment]
Addressed in #17
