### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by wdrich** [Xabadu/react-native-jest-mocks#7]
where may i use "mocks.initAll();"?
is there any example?

**Comment by Xabadu** [comment]
Hey @wdrich. I added an Example app that you can check to see how it works.

What you need to do in any case, is create a jest-setup.js file in the root of your project and inside that file import the module following the "Usage" instructions.

Afterwards, if you haven't already, add this to your package.json file, inside the "jest" section:

`"setupFiles": [
      "./jest-setup.js"
    ]
`
Let me know if you have any more questions, thanks for using this!
